test: value without brackets

diff --git a/.github/workflows/releaseprocess.yml b/.github/workflows/releaseprocess.yml
--- a/.github/workflows/releaseprocess.yml
+++ b/.github/workflows/releaseprocess.yml
@@ -44,13 +44,13 @@ jobs:
       - name: "Tests: unit"
         id: unit_test
         run: |
-          npm run test-unit-ci && echo "UNIT_TEST_RESULT='PASSED'" >> $GITHUB_ENV || echo "UNIT_TEST_RESULT='FAILED'" >> $GITHUB_ENV
+          npm run test-unit-ci && echo "UNIT_TEST_RESULT=PASSED" >> $GITHUB_ENV || echo "UNIT_TEST_RESULT=FAILED" >> $GITHUB_ENV
         continue-on-error: true
 
       - name: "Tests: e2e"
         id: e2e_test
         run: |
-          npm run test-e2e-ci && echo "E2E_TEST_RESULT='PASSED'" >> $GITHUB_ENV || echo "E2E_TEST_RESULT='FAILED'" >> $GITHUB_ENV
+          npm run test-e2e-ci && echo "E2E_TEST_RESULT=PASSED" >> $GITHUB_ENV || echo "E2E_TEST_RESULT=FAILED" >> $GITHUB_ENV
         continue-on-error: true
 
       - name: Upload Artifacts (unit tests)
